# Generated by Django 4.2.7 on 2023-12-15 19:28

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('educative', 'Educative'), ('social', 'Social'), ('entertainment', 'Entertainment'), ('health', 'Health'), ('technology', 'Technology'), ('politics', 'Politics'), ('sports', 'Sports'), ('arts', 'Arts & Culture'), ('business', 'Business & Finance'), ('science', 'Science'), ('lifestyle', 'Lifestyle'), ('travel', 'Travel'), ('food', 'Food & Drink'), ('environment', 'Environment'), ('history', 'History'), ('psychology', 'Psychology'), ('relationships', 'Relationships'), ('automotive', 'Automotive'), ('economy', 'Economy'), ('pets', 'Pets & Animals'), ('spirituality', 'Spirituality'), ('gaming', 'Gaming'), ('literature', 'Literature'), ('fashion', 'Fashion'), ('real_estate', 'Real Estate')], max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog-images/')),
                ('title', models.CharField(max_length=500)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('intro', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='intro')),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='body')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='blog.article')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.article')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='blog.comments')),
            ],
        ),
    ]
